// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search-request.proto

package nl.toefel.java.protobuf;

public final class Search {
  private Search() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string query = 1;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>string query = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>int32 page_number = 2;</code>
     */
    int getPageNumber();

    /**
     * <code>int32 result_per_page = 3;</code>
     */
    int getResultPerPage();

    /**
     * <code>float latitude = 4;</code>
     */
    float getLatitude();

    /**
     * <code>float longitude = 5;</code>
     */
    float getLongitude();

    /**
     * <code>.SearchRequest.ShipmentType shipmentType = 6;</code>
     */
    int getShipmentTypeValue();
    /**
     * <code>.SearchRequest.ShipmentType shipmentType = 6;</code>
     */
    nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType getShipmentType();
  }
  /**
   * Protobuf type {@code SearchRequest}
   */
  public  static final class SearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SearchRequest)
      SearchRequestOrBuilder {
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchRequest() {
      query_ = "";
      pageNumber_ = 0;
      resultPerPage_ = 0;
      latitude_ = 0F;
      longitude_ = 0F;
      shipmentType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              query_ = s;
              break;
            }
            case 16: {

              pageNumber_ = input.readInt32();
              break;
            }
            case 24: {

              resultPerPage_ = input.readInt32();
              break;
            }
            case 37: {

              latitude_ = input.readFloat();
              break;
            }
            case 45: {

              longitude_ = input.readFloat();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              shipmentType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.toefel.java.protobuf.Search.internal_static_SearchRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.toefel.java.protobuf.Search.internal_static_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.toefel.java.protobuf.Search.SearchRequest.class, nl.toefel.java.protobuf.Search.SearchRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code SearchRequest.ShipmentType}
     */
    public enum ShipmentType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>DELIVERY = 1;</code>
       */
      DELIVERY(1),
      /**
       * <code>PICKUP = 2;</code>
       */
      PICKUP(2),
      /**
       * <code>EXPRESSER = 3;</code>
       */
      EXPRESSER(3),
      /**
       * <code>PALLET = 4;</code>
       */
      PALLET(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>DELIVERY = 1;</code>
       */
      public static final int DELIVERY_VALUE = 1;
      /**
       * <code>PICKUP = 2;</code>
       */
      public static final int PICKUP_VALUE = 2;
      /**
       * <code>EXPRESSER = 3;</code>
       */
      public static final int EXPRESSER_VALUE = 3;
      /**
       * <code>PALLET = 4;</code>
       */
      public static final int PALLET_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ShipmentType valueOf(int value) {
        return forNumber(value);
      }

      public static ShipmentType forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return DELIVERY;
          case 2: return PICKUP;
          case 3: return EXPRESSER;
          case 4: return PALLET;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ShipmentType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ShipmentType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ShipmentType>() {
              public ShipmentType findValueByNumber(int number) {
                return ShipmentType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return nl.toefel.java.protobuf.Search.SearchRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final ShipmentType[] VALUES = values();

      public static ShipmentType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ShipmentType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:SearchRequest.ShipmentType)
    }

    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <code>string query = 1;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <code>string query = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
    private int pageNumber_;
    /**
     * <code>int32 page_number = 2;</code>
     */
    public int getPageNumber() {
      return pageNumber_;
    }

    public static final int RESULT_PER_PAGE_FIELD_NUMBER = 3;
    private int resultPerPage_;
    /**
     * <code>int32 result_per_page = 3;</code>
     */
    public int getResultPerPage() {
      return resultPerPage_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 4;
    private float latitude_;
    /**
     * <code>float latitude = 4;</code>
     */
    public float getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 5;
    private float longitude_;
    /**
     * <code>float longitude = 5;</code>
     */
    public float getLongitude() {
      return longitude_;
    }

    public static final int SHIPMENTTYPE_FIELD_NUMBER = 6;
    private int shipmentType_;
    /**
     * <code>.SearchRequest.ShipmentType shipmentType = 6;</code>
     */
    public int getShipmentTypeValue() {
      return shipmentType_;
    }
    /**
     * <code>.SearchRequest.ShipmentType shipmentType = 6;</code>
     */
    public nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType getShipmentType() {
      nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType result = nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType.valueOf(shipmentType_);
      return result == null ? nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getQueryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      if (pageNumber_ != 0) {
        output.writeInt32(2, pageNumber_);
      }
      if (resultPerPage_ != 0) {
        output.writeInt32(3, resultPerPage_);
      }
      if (latitude_ != 0F) {
        output.writeFloat(4, latitude_);
      }
      if (longitude_ != 0F) {
        output.writeFloat(5, longitude_);
      }
      if (shipmentType_ != nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType.UNKNOWN.getNumber()) {
        output.writeEnum(6, shipmentType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getQueryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      if (pageNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNumber_);
      }
      if (resultPerPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resultPerPage_);
      }
      if (latitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, latitude_);
      }
      if (longitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, longitude_);
      }
      if (shipmentType_ != nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, shipmentType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nl.toefel.java.protobuf.Search.SearchRequest)) {
        return super.equals(obj);
      }
      nl.toefel.java.protobuf.Search.SearchRequest other = (nl.toefel.java.protobuf.Search.SearchRequest) obj;

      boolean result = true;
      result = result && getQuery()
          .equals(other.getQuery());
      result = result && (getPageNumber()
          == other.getPageNumber());
      result = result && (getResultPerPage()
          == other.getResultPerPage());
      result = result && (
          java.lang.Float.floatToIntBits(getLatitude())
          == java.lang.Float.floatToIntBits(
              other.getLatitude()));
      result = result && (
          java.lang.Float.floatToIntBits(getLongitude())
          == java.lang.Float.floatToIntBits(
              other.getLongitude()));
      result = result && shipmentType_ == other.shipmentType_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPageNumber();
      hash = (37 * hash) + RESULT_PER_PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResultPerPage();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLatitude());
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLongitude());
      hash = (37 * hash) + SHIPMENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + shipmentType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nl.toefel.java.protobuf.Search.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.toefel.java.protobuf.Search.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.toefel.java.protobuf.Search.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.toefel.java.protobuf.Search.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.toefel.java.protobuf.Search.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.toefel.java.protobuf.Search.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.toefel.java.protobuf.Search.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nl.toefel.java.protobuf.Search.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.toefel.java.protobuf.Search.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.toefel.java.protobuf.Search.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nl.toefel.java.protobuf.Search.SearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SearchRequest)
        nl.toefel.java.protobuf.Search.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.toefel.java.protobuf.Search.internal_static_SearchRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.toefel.java.protobuf.Search.internal_static_SearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nl.toefel.java.protobuf.Search.SearchRequest.class, nl.toefel.java.protobuf.Search.SearchRequest.Builder.class);
      }

      // Construct using nl.toefel.java.protobuf.Search.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        query_ = "";

        pageNumber_ = 0;

        resultPerPage_ = 0;

        latitude_ = 0F;

        longitude_ = 0F;

        shipmentType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nl.toefel.java.protobuf.Search.internal_static_SearchRequest_descriptor;
      }

      public nl.toefel.java.protobuf.Search.SearchRequest getDefaultInstanceForType() {
        return nl.toefel.java.protobuf.Search.SearchRequest.getDefaultInstance();
      }

      public nl.toefel.java.protobuf.Search.SearchRequest build() {
        nl.toefel.java.protobuf.Search.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nl.toefel.java.protobuf.Search.SearchRequest buildPartial() {
        nl.toefel.java.protobuf.Search.SearchRequest result = new nl.toefel.java.protobuf.Search.SearchRequest(this);
        result.query_ = query_;
        result.pageNumber_ = pageNumber_;
        result.resultPerPage_ = resultPerPage_;
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        result.shipmentType_ = shipmentType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.toefel.java.protobuf.Search.SearchRequest) {
          return mergeFrom((nl.toefel.java.protobuf.Search.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nl.toefel.java.protobuf.Search.SearchRequest other) {
        if (other == nl.toefel.java.protobuf.Search.SearchRequest.getDefaultInstance()) return this;
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          onChanged();
        }
        if (other.getPageNumber() != 0) {
          setPageNumber(other.getPageNumber());
        }
        if (other.getResultPerPage() != 0) {
          setResultPerPage(other.getResultPerPage());
        }
        if (other.getLatitude() != 0F) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0F) {
          setLongitude(other.getLongitude());
        }
        if (other.shipmentType_ != 0) {
          setShipmentTypeValue(other.getShipmentTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nl.toefel.java.protobuf.Search.SearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nl.toefel.java.protobuf.Search.SearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object query_ = "";
      /**
       * <code>string query = 1;</code>
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string query = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string query = 1;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string query = 1;</code>
       */
      public Builder clearQuery() {
        
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>string query = 1;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        query_ = value;
        onChanged();
        return this;
      }

      private int pageNumber_ ;
      /**
       * <code>int32 page_number = 2;</code>
       */
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <code>int32 page_number = 2;</code>
       */
      public Builder setPageNumber(int value) {
        
        pageNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 page_number = 2;</code>
       */
      public Builder clearPageNumber() {
        
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      private int resultPerPage_ ;
      /**
       * <code>int32 result_per_page = 3;</code>
       */
      public int getResultPerPage() {
        return resultPerPage_;
      }
      /**
       * <code>int32 result_per_page = 3;</code>
       */
      public Builder setResultPerPage(int value) {
        
        resultPerPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result_per_page = 3;</code>
       */
      public Builder clearResultPerPage() {
        
        resultPerPage_ = 0;
        onChanged();
        return this;
      }

      private float latitude_ ;
      /**
       * <code>float latitude = 4;</code>
       */
      public float getLatitude() {
        return latitude_;
      }
      /**
       * <code>float latitude = 4;</code>
       */
      public Builder setLatitude(float value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float latitude = 4;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0F;
        onChanged();
        return this;
      }

      private float longitude_ ;
      /**
       * <code>float longitude = 5;</code>
       */
      public float getLongitude() {
        return longitude_;
      }
      /**
       * <code>float longitude = 5;</code>
       */
      public Builder setLongitude(float value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float longitude = 5;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0F;
        onChanged();
        return this;
      }

      private int shipmentType_ = 0;
      /**
       * <code>.SearchRequest.ShipmentType shipmentType = 6;</code>
       */
      public int getShipmentTypeValue() {
        return shipmentType_;
      }
      /**
       * <code>.SearchRequest.ShipmentType shipmentType = 6;</code>
       */
      public Builder setShipmentTypeValue(int value) {
        shipmentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.SearchRequest.ShipmentType shipmentType = 6;</code>
       */
      public nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType getShipmentType() {
        nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType result = nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType.valueOf(shipmentType_);
        return result == null ? nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType.UNRECOGNIZED : result;
      }
      /**
       * <code>.SearchRequest.ShipmentType shipmentType = 6;</code>
       */
      public Builder setShipmentType(nl.toefel.java.protobuf.Search.SearchRequest.ShipmentType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        shipmentType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.SearchRequest.ShipmentType shipmentType = 6;</code>
       */
      public Builder clearShipmentType() {
        
        shipmentType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SearchRequest)
    }

    // @@protoc_insertion_point(class_scope:SearchRequest)
    private static final nl.toefel.java.protobuf.Search.SearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nl.toefel.java.protobuf.Search.SearchRequest();
    }

    public static nl.toefel.java.protobuf.Search.SearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
      public SearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    public nl.toefel.java.protobuf.Search.SearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface REOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RE)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string htSerialNr = 1;</code>
     */
    java.lang.String getHtSerialNr();
    /**
     * <code>string htSerialNr = 1;</code>
     */
    com.google.protobuf.ByteString
        getHtSerialNrBytes();

    /**
     * <code>string routeNr = 2;</code>
     */
    java.lang.String getRouteNr();
    /**
     * <code>string routeNr = 2;</code>
     */
    com.google.protobuf.ByteString
        getRouteNrBytes();

    /**
     * <code>string activityCode = 3;</code>
     */
    java.lang.String getActivityCode();
    /**
     * <code>string activityCode = 3;</code>
     */
    com.google.protobuf.ByteString
        getActivityCodeBytes();

    /**
     * <code>string ritNr = 4;</code>
     */
    java.lang.String getRitNr();
    /**
     * <code>string ritNr = 4;</code>
     */
    com.google.protobuf.ByteString
        getRitNrBytes();

    /**
     * <code>string driver = 5;</code>
     */
    java.lang.String getDriver();
    /**
     * <code>string driver = 5;</code>
     */
    com.google.protobuf.ByteString
        getDriverBytes();

    /**
     * <code>string shipmentNr = 6;</code>
     */
    java.lang.String getShipmentNr();
    /**
     * <code>string shipmentNr = 6;</code>
     */
    com.google.protobuf.ByteString
        getShipmentNrBytes();

    /**
     * <code>int64 timestamp = 7;</code>
     */
    long getTimestamp();

    /**
     * <code>bool pickupAcceptedByDriver = 8;</code>
     */
    boolean getPickupAcceptedByDriver();

    /**
     * <code>bool pickupCancelledAcceptedByDriver = 9;</code>
     */
    boolean getPickupCancelledAcceptedByDriver();

    /**
     * <code>bool pickedUp = 10;</code>
     */
    boolean getPickedUp();

    /**
     * <code>int32 loadedHalfFloorspaces = 11;</code>
     */
    int getLoadedHalfFloorspaces();

    /**
     * <code>bool recipientNotHome = 12;</code>
     */
    boolean getRecipientNotHome();

    /**
     * <code>bool vacation = 13;</code>
     */
    boolean getVacation();

    /**
     * <code>int64 newPickupDate = 14;</code>
     */
    long getNewPickupDate();

    /**
     * <code>bool unknownAddress = 15;</code>
     */
    boolean getUnknownAddress();

    /**
     * <code>bool unknownAddressee = 16;</code>
     */
    boolean getUnknownAddressee();

    /**
     * <code>bool noGoods = 17;</code>
     */
    boolean getNoGoods();
  }
  /**
   * Protobuf type {@code RE}
   */
  public  static final class RE extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RE)
      REOrBuilder {
    // Use RE.newBuilder() to construct.
    private RE(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RE() {
      htSerialNr_ = "";
      routeNr_ = "";
      activityCode_ = "";
      ritNr_ = "";
      driver_ = "";
      shipmentNr_ = "";
      timestamp_ = 0L;
      pickupAcceptedByDriver_ = false;
      pickupCancelledAcceptedByDriver_ = false;
      pickedUp_ = false;
      loadedHalfFloorspaces_ = 0;
      recipientNotHome_ = false;
      vacation_ = false;
      newPickupDate_ = 0L;
      unknownAddress_ = false;
      unknownAddressee_ = false;
      noGoods_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RE(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              htSerialNr_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              routeNr_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              activityCode_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              ritNr_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              driver_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              shipmentNr_ = s;
              break;
            }
            case 56: {

              timestamp_ = input.readInt64();
              break;
            }
            case 64: {

              pickupAcceptedByDriver_ = input.readBool();
              break;
            }
            case 72: {

              pickupCancelledAcceptedByDriver_ = input.readBool();
              break;
            }
            case 80: {

              pickedUp_ = input.readBool();
              break;
            }
            case 88: {

              loadedHalfFloorspaces_ = input.readInt32();
              break;
            }
            case 96: {

              recipientNotHome_ = input.readBool();
              break;
            }
            case 104: {

              vacation_ = input.readBool();
              break;
            }
            case 112: {

              newPickupDate_ = input.readInt64();
              break;
            }
            case 120: {

              unknownAddress_ = input.readBool();
              break;
            }
            case 128: {

              unknownAddressee_ = input.readBool();
              break;
            }
            case 136: {

              noGoods_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.toefel.java.protobuf.Search.internal_static_RE_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.toefel.java.protobuf.Search.internal_static_RE_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.toefel.java.protobuf.Search.RE.class, nl.toefel.java.protobuf.Search.RE.Builder.class);
    }

    public static final int HTSERIALNR_FIELD_NUMBER = 1;
    private volatile java.lang.Object htSerialNr_;
    /**
     * <code>string htSerialNr = 1;</code>
     */
    public java.lang.String getHtSerialNr() {
      java.lang.Object ref = htSerialNr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        htSerialNr_ = s;
        return s;
      }
    }
    /**
     * <code>string htSerialNr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHtSerialNrBytes() {
      java.lang.Object ref = htSerialNr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        htSerialNr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUTENR_FIELD_NUMBER = 2;
    private volatile java.lang.Object routeNr_;
    /**
     * <code>string routeNr = 2;</code>
     */
    public java.lang.String getRouteNr() {
      java.lang.Object ref = routeNr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routeNr_ = s;
        return s;
      }
    }
    /**
     * <code>string routeNr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRouteNrBytes() {
      java.lang.Object ref = routeNr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routeNr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIVITYCODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object activityCode_;
    /**
     * <code>string activityCode = 3;</code>
     */
    public java.lang.String getActivityCode() {
      java.lang.Object ref = activityCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        activityCode_ = s;
        return s;
      }
    }
    /**
     * <code>string activityCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getActivityCodeBytes() {
      java.lang.Object ref = activityCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activityCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RITNR_FIELD_NUMBER = 4;
    private volatile java.lang.Object ritNr_;
    /**
     * <code>string ritNr = 4;</code>
     */
    public java.lang.String getRitNr() {
      java.lang.Object ref = ritNr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ritNr_ = s;
        return s;
      }
    }
    /**
     * <code>string ritNr = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRitNrBytes() {
      java.lang.Object ref = ritNr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ritNr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DRIVER_FIELD_NUMBER = 5;
    private volatile java.lang.Object driver_;
    /**
     * <code>string driver = 5;</code>
     */
    public java.lang.String getDriver() {
      java.lang.Object ref = driver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        driver_ = s;
        return s;
      }
    }
    /**
     * <code>string driver = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDriverBytes() {
      java.lang.Object ref = driver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        driver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHIPMENTNR_FIELD_NUMBER = 6;
    private volatile java.lang.Object shipmentNr_;
    /**
     * <code>string shipmentNr = 6;</code>
     */
    public java.lang.String getShipmentNr() {
      java.lang.Object ref = shipmentNr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shipmentNr_ = s;
        return s;
      }
    }
    /**
     * <code>string shipmentNr = 6;</code>
     */
    public com.google.protobuf.ByteString
        getShipmentNrBytes() {
      java.lang.Object ref = shipmentNr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shipmentNr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 7;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int PICKUPACCEPTEDBYDRIVER_FIELD_NUMBER = 8;
    private boolean pickupAcceptedByDriver_;
    /**
     * <code>bool pickupAcceptedByDriver = 8;</code>
     */
    public boolean getPickupAcceptedByDriver() {
      return pickupAcceptedByDriver_;
    }

    public static final int PICKUPCANCELLEDACCEPTEDBYDRIVER_FIELD_NUMBER = 9;
    private boolean pickupCancelledAcceptedByDriver_;
    /**
     * <code>bool pickupCancelledAcceptedByDriver = 9;</code>
     */
    public boolean getPickupCancelledAcceptedByDriver() {
      return pickupCancelledAcceptedByDriver_;
    }

    public static final int PICKEDUP_FIELD_NUMBER = 10;
    private boolean pickedUp_;
    /**
     * <code>bool pickedUp = 10;</code>
     */
    public boolean getPickedUp() {
      return pickedUp_;
    }

    public static final int LOADEDHALFFLOORSPACES_FIELD_NUMBER = 11;
    private int loadedHalfFloorspaces_;
    /**
     * <code>int32 loadedHalfFloorspaces = 11;</code>
     */
    public int getLoadedHalfFloorspaces() {
      return loadedHalfFloorspaces_;
    }

    public static final int RECIPIENTNOTHOME_FIELD_NUMBER = 12;
    private boolean recipientNotHome_;
    /**
     * <code>bool recipientNotHome = 12;</code>
     */
    public boolean getRecipientNotHome() {
      return recipientNotHome_;
    }

    public static final int VACATION_FIELD_NUMBER = 13;
    private boolean vacation_;
    /**
     * <code>bool vacation = 13;</code>
     */
    public boolean getVacation() {
      return vacation_;
    }

    public static final int NEWPICKUPDATE_FIELD_NUMBER = 14;
    private long newPickupDate_;
    /**
     * <code>int64 newPickupDate = 14;</code>
     */
    public long getNewPickupDate() {
      return newPickupDate_;
    }

    public static final int UNKNOWNADDRESS_FIELD_NUMBER = 15;
    private boolean unknownAddress_;
    /**
     * <code>bool unknownAddress = 15;</code>
     */
    public boolean getUnknownAddress() {
      return unknownAddress_;
    }

    public static final int UNKNOWNADDRESSEE_FIELD_NUMBER = 16;
    private boolean unknownAddressee_;
    /**
     * <code>bool unknownAddressee = 16;</code>
     */
    public boolean getUnknownAddressee() {
      return unknownAddressee_;
    }

    public static final int NOGOODS_FIELD_NUMBER = 17;
    private boolean noGoods_;
    /**
     * <code>bool noGoods = 17;</code>
     */
    public boolean getNoGoods() {
      return noGoods_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHtSerialNrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, htSerialNr_);
      }
      if (!getRouteNrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, routeNr_);
      }
      if (!getActivityCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, activityCode_);
      }
      if (!getRitNrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ritNr_);
      }
      if (!getDriverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, driver_);
      }
      if (!getShipmentNrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, shipmentNr_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(7, timestamp_);
      }
      if (pickupAcceptedByDriver_ != false) {
        output.writeBool(8, pickupAcceptedByDriver_);
      }
      if (pickupCancelledAcceptedByDriver_ != false) {
        output.writeBool(9, pickupCancelledAcceptedByDriver_);
      }
      if (pickedUp_ != false) {
        output.writeBool(10, pickedUp_);
      }
      if (loadedHalfFloorspaces_ != 0) {
        output.writeInt32(11, loadedHalfFloorspaces_);
      }
      if (recipientNotHome_ != false) {
        output.writeBool(12, recipientNotHome_);
      }
      if (vacation_ != false) {
        output.writeBool(13, vacation_);
      }
      if (newPickupDate_ != 0L) {
        output.writeInt64(14, newPickupDate_);
      }
      if (unknownAddress_ != false) {
        output.writeBool(15, unknownAddress_);
      }
      if (unknownAddressee_ != false) {
        output.writeBool(16, unknownAddressee_);
      }
      if (noGoods_ != false) {
        output.writeBool(17, noGoods_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHtSerialNrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, htSerialNr_);
      }
      if (!getRouteNrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, routeNr_);
      }
      if (!getActivityCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, activityCode_);
      }
      if (!getRitNrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ritNr_);
      }
      if (!getDriverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, driver_);
      }
      if (!getShipmentNrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, shipmentNr_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timestamp_);
      }
      if (pickupAcceptedByDriver_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, pickupAcceptedByDriver_);
      }
      if (pickupCancelledAcceptedByDriver_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, pickupCancelledAcceptedByDriver_);
      }
      if (pickedUp_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, pickedUp_);
      }
      if (loadedHalfFloorspaces_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, loadedHalfFloorspaces_);
      }
      if (recipientNotHome_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, recipientNotHome_);
      }
      if (vacation_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, vacation_);
      }
      if (newPickupDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, newPickupDate_);
      }
      if (unknownAddress_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, unknownAddress_);
      }
      if (unknownAddressee_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, unknownAddressee_);
      }
      if (noGoods_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(17, noGoods_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nl.toefel.java.protobuf.Search.RE)) {
        return super.equals(obj);
      }
      nl.toefel.java.protobuf.Search.RE other = (nl.toefel.java.protobuf.Search.RE) obj;

      boolean result = true;
      result = result && getHtSerialNr()
          .equals(other.getHtSerialNr());
      result = result && getRouteNr()
          .equals(other.getRouteNr());
      result = result && getActivityCode()
          .equals(other.getActivityCode());
      result = result && getRitNr()
          .equals(other.getRitNr());
      result = result && getDriver()
          .equals(other.getDriver());
      result = result && getShipmentNr()
          .equals(other.getShipmentNr());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && (getPickupAcceptedByDriver()
          == other.getPickupAcceptedByDriver());
      result = result && (getPickupCancelledAcceptedByDriver()
          == other.getPickupCancelledAcceptedByDriver());
      result = result && (getPickedUp()
          == other.getPickedUp());
      result = result && (getLoadedHalfFloorspaces()
          == other.getLoadedHalfFloorspaces());
      result = result && (getRecipientNotHome()
          == other.getRecipientNotHome());
      result = result && (getVacation()
          == other.getVacation());
      result = result && (getNewPickupDate()
          == other.getNewPickupDate());
      result = result && (getUnknownAddress()
          == other.getUnknownAddress());
      result = result && (getUnknownAddressee()
          == other.getUnknownAddressee());
      result = result && (getNoGoods()
          == other.getNoGoods());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HTSERIALNR_FIELD_NUMBER;
      hash = (53 * hash) + getHtSerialNr().hashCode();
      hash = (37 * hash) + ROUTENR_FIELD_NUMBER;
      hash = (53 * hash) + getRouteNr().hashCode();
      hash = (37 * hash) + ACTIVITYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getActivityCode().hashCode();
      hash = (37 * hash) + RITNR_FIELD_NUMBER;
      hash = (53 * hash) + getRitNr().hashCode();
      hash = (37 * hash) + DRIVER_FIELD_NUMBER;
      hash = (53 * hash) + getDriver().hashCode();
      hash = (37 * hash) + SHIPMENTNR_FIELD_NUMBER;
      hash = (53 * hash) + getShipmentNr().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + PICKUPACCEPTEDBYDRIVER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPickupAcceptedByDriver());
      hash = (37 * hash) + PICKUPCANCELLEDACCEPTEDBYDRIVER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPickupCancelledAcceptedByDriver());
      hash = (37 * hash) + PICKEDUP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPickedUp());
      hash = (37 * hash) + LOADEDHALFFLOORSPACES_FIELD_NUMBER;
      hash = (53 * hash) + getLoadedHalfFloorspaces();
      hash = (37 * hash) + RECIPIENTNOTHOME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRecipientNotHome());
      hash = (37 * hash) + VACATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVacation());
      hash = (37 * hash) + NEWPICKUPDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNewPickupDate());
      hash = (37 * hash) + UNKNOWNADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUnknownAddress());
      hash = (37 * hash) + UNKNOWNADDRESSEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUnknownAddressee());
      hash = (37 * hash) + NOGOODS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNoGoods());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nl.toefel.java.protobuf.Search.RE parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.toefel.java.protobuf.Search.RE parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.toefel.java.protobuf.Search.RE parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nl.toefel.java.protobuf.Search.RE parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nl.toefel.java.protobuf.Search.RE parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.toefel.java.protobuf.Search.RE parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.toefel.java.protobuf.Search.RE parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nl.toefel.java.protobuf.Search.RE parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nl.toefel.java.protobuf.Search.RE parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nl.toefel.java.protobuf.Search.RE parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nl.toefel.java.protobuf.Search.RE prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RE}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RE)
        nl.toefel.java.protobuf.Search.REOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nl.toefel.java.protobuf.Search.internal_static_RE_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nl.toefel.java.protobuf.Search.internal_static_RE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nl.toefel.java.protobuf.Search.RE.class, nl.toefel.java.protobuf.Search.RE.Builder.class);
      }

      // Construct using nl.toefel.java.protobuf.Search.RE.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        htSerialNr_ = "";

        routeNr_ = "";

        activityCode_ = "";

        ritNr_ = "";

        driver_ = "";

        shipmentNr_ = "";

        timestamp_ = 0L;

        pickupAcceptedByDriver_ = false;

        pickupCancelledAcceptedByDriver_ = false;

        pickedUp_ = false;

        loadedHalfFloorspaces_ = 0;

        recipientNotHome_ = false;

        vacation_ = false;

        newPickupDate_ = 0L;

        unknownAddress_ = false;

        unknownAddressee_ = false;

        noGoods_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nl.toefel.java.protobuf.Search.internal_static_RE_descriptor;
      }

      public nl.toefel.java.protobuf.Search.RE getDefaultInstanceForType() {
        return nl.toefel.java.protobuf.Search.RE.getDefaultInstance();
      }

      public nl.toefel.java.protobuf.Search.RE build() {
        nl.toefel.java.protobuf.Search.RE result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nl.toefel.java.protobuf.Search.RE buildPartial() {
        nl.toefel.java.protobuf.Search.RE result = new nl.toefel.java.protobuf.Search.RE(this);
        result.htSerialNr_ = htSerialNr_;
        result.routeNr_ = routeNr_;
        result.activityCode_ = activityCode_;
        result.ritNr_ = ritNr_;
        result.driver_ = driver_;
        result.shipmentNr_ = shipmentNr_;
        result.timestamp_ = timestamp_;
        result.pickupAcceptedByDriver_ = pickupAcceptedByDriver_;
        result.pickupCancelledAcceptedByDriver_ = pickupCancelledAcceptedByDriver_;
        result.pickedUp_ = pickedUp_;
        result.loadedHalfFloorspaces_ = loadedHalfFloorspaces_;
        result.recipientNotHome_ = recipientNotHome_;
        result.vacation_ = vacation_;
        result.newPickupDate_ = newPickupDate_;
        result.unknownAddress_ = unknownAddress_;
        result.unknownAddressee_ = unknownAddressee_;
        result.noGoods_ = noGoods_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.toefel.java.protobuf.Search.RE) {
          return mergeFrom((nl.toefel.java.protobuf.Search.RE)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nl.toefel.java.protobuf.Search.RE other) {
        if (other == nl.toefel.java.protobuf.Search.RE.getDefaultInstance()) return this;
        if (!other.getHtSerialNr().isEmpty()) {
          htSerialNr_ = other.htSerialNr_;
          onChanged();
        }
        if (!other.getRouteNr().isEmpty()) {
          routeNr_ = other.routeNr_;
          onChanged();
        }
        if (!other.getActivityCode().isEmpty()) {
          activityCode_ = other.activityCode_;
          onChanged();
        }
        if (!other.getRitNr().isEmpty()) {
          ritNr_ = other.ritNr_;
          onChanged();
        }
        if (!other.getDriver().isEmpty()) {
          driver_ = other.driver_;
          onChanged();
        }
        if (!other.getShipmentNr().isEmpty()) {
          shipmentNr_ = other.shipmentNr_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getPickupAcceptedByDriver() != false) {
          setPickupAcceptedByDriver(other.getPickupAcceptedByDriver());
        }
        if (other.getPickupCancelledAcceptedByDriver() != false) {
          setPickupCancelledAcceptedByDriver(other.getPickupCancelledAcceptedByDriver());
        }
        if (other.getPickedUp() != false) {
          setPickedUp(other.getPickedUp());
        }
        if (other.getLoadedHalfFloorspaces() != 0) {
          setLoadedHalfFloorspaces(other.getLoadedHalfFloorspaces());
        }
        if (other.getRecipientNotHome() != false) {
          setRecipientNotHome(other.getRecipientNotHome());
        }
        if (other.getVacation() != false) {
          setVacation(other.getVacation());
        }
        if (other.getNewPickupDate() != 0L) {
          setNewPickupDate(other.getNewPickupDate());
        }
        if (other.getUnknownAddress() != false) {
          setUnknownAddress(other.getUnknownAddress());
        }
        if (other.getUnknownAddressee() != false) {
          setUnknownAddressee(other.getUnknownAddressee());
        }
        if (other.getNoGoods() != false) {
          setNoGoods(other.getNoGoods());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nl.toefel.java.protobuf.Search.RE parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nl.toefel.java.protobuf.Search.RE) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object htSerialNr_ = "";
      /**
       * <code>string htSerialNr = 1;</code>
       */
      public java.lang.String getHtSerialNr() {
        java.lang.Object ref = htSerialNr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          htSerialNr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string htSerialNr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHtSerialNrBytes() {
        java.lang.Object ref = htSerialNr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          htSerialNr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string htSerialNr = 1;</code>
       */
      public Builder setHtSerialNr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        htSerialNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string htSerialNr = 1;</code>
       */
      public Builder clearHtSerialNr() {
        
        htSerialNr_ = getDefaultInstance().getHtSerialNr();
        onChanged();
        return this;
      }
      /**
       * <code>string htSerialNr = 1;</code>
       */
      public Builder setHtSerialNrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        htSerialNr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object routeNr_ = "";
      /**
       * <code>string routeNr = 2;</code>
       */
      public java.lang.String getRouteNr() {
        java.lang.Object ref = routeNr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          routeNr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string routeNr = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRouteNrBytes() {
        java.lang.Object ref = routeNr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          routeNr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string routeNr = 2;</code>
       */
      public Builder setRouteNr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        routeNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string routeNr = 2;</code>
       */
      public Builder clearRouteNr() {
        
        routeNr_ = getDefaultInstance().getRouteNr();
        onChanged();
        return this;
      }
      /**
       * <code>string routeNr = 2;</code>
       */
      public Builder setRouteNrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        routeNr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object activityCode_ = "";
      /**
       * <code>string activityCode = 3;</code>
       */
      public java.lang.String getActivityCode() {
        java.lang.Object ref = activityCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          activityCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string activityCode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getActivityCodeBytes() {
        java.lang.Object ref = activityCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          activityCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string activityCode = 3;</code>
       */
      public Builder setActivityCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        activityCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string activityCode = 3;</code>
       */
      public Builder clearActivityCode() {
        
        activityCode_ = getDefaultInstance().getActivityCode();
        onChanged();
        return this;
      }
      /**
       * <code>string activityCode = 3;</code>
       */
      public Builder setActivityCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        activityCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ritNr_ = "";
      /**
       * <code>string ritNr = 4;</code>
       */
      public java.lang.String getRitNr() {
        java.lang.Object ref = ritNr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ritNr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ritNr = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRitNrBytes() {
        java.lang.Object ref = ritNr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ritNr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ritNr = 4;</code>
       */
      public Builder setRitNr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ritNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ritNr = 4;</code>
       */
      public Builder clearRitNr() {
        
        ritNr_ = getDefaultInstance().getRitNr();
        onChanged();
        return this;
      }
      /**
       * <code>string ritNr = 4;</code>
       */
      public Builder setRitNrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ritNr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object driver_ = "";
      /**
       * <code>string driver = 5;</code>
       */
      public java.lang.String getDriver() {
        java.lang.Object ref = driver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          driver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string driver = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDriverBytes() {
        java.lang.Object ref = driver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          driver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string driver = 5;</code>
       */
      public Builder setDriver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        driver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string driver = 5;</code>
       */
      public Builder clearDriver() {
        
        driver_ = getDefaultInstance().getDriver();
        onChanged();
        return this;
      }
      /**
       * <code>string driver = 5;</code>
       */
      public Builder setDriverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        driver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shipmentNr_ = "";
      /**
       * <code>string shipmentNr = 6;</code>
       */
      public java.lang.String getShipmentNr() {
        java.lang.Object ref = shipmentNr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shipmentNr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string shipmentNr = 6;</code>
       */
      public com.google.protobuf.ByteString
          getShipmentNrBytes() {
        java.lang.Object ref = shipmentNr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shipmentNr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string shipmentNr = 6;</code>
       */
      public Builder setShipmentNr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shipmentNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string shipmentNr = 6;</code>
       */
      public Builder clearShipmentNr() {
        
        shipmentNr_ = getDefaultInstance().getShipmentNr();
        onChanged();
        return this;
      }
      /**
       * <code>string shipmentNr = 6;</code>
       */
      public Builder setShipmentNrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shipmentNr_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 7;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 7;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 7;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private boolean pickupAcceptedByDriver_ ;
      /**
       * <code>bool pickupAcceptedByDriver = 8;</code>
       */
      public boolean getPickupAcceptedByDriver() {
        return pickupAcceptedByDriver_;
      }
      /**
       * <code>bool pickupAcceptedByDriver = 8;</code>
       */
      public Builder setPickupAcceptedByDriver(boolean value) {
        
        pickupAcceptedByDriver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool pickupAcceptedByDriver = 8;</code>
       */
      public Builder clearPickupAcceptedByDriver() {
        
        pickupAcceptedByDriver_ = false;
        onChanged();
        return this;
      }

      private boolean pickupCancelledAcceptedByDriver_ ;
      /**
       * <code>bool pickupCancelledAcceptedByDriver = 9;</code>
       */
      public boolean getPickupCancelledAcceptedByDriver() {
        return pickupCancelledAcceptedByDriver_;
      }
      /**
       * <code>bool pickupCancelledAcceptedByDriver = 9;</code>
       */
      public Builder setPickupCancelledAcceptedByDriver(boolean value) {
        
        pickupCancelledAcceptedByDriver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool pickupCancelledAcceptedByDriver = 9;</code>
       */
      public Builder clearPickupCancelledAcceptedByDriver() {
        
        pickupCancelledAcceptedByDriver_ = false;
        onChanged();
        return this;
      }

      private boolean pickedUp_ ;
      /**
       * <code>bool pickedUp = 10;</code>
       */
      public boolean getPickedUp() {
        return pickedUp_;
      }
      /**
       * <code>bool pickedUp = 10;</code>
       */
      public Builder setPickedUp(boolean value) {
        
        pickedUp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool pickedUp = 10;</code>
       */
      public Builder clearPickedUp() {
        
        pickedUp_ = false;
        onChanged();
        return this;
      }

      private int loadedHalfFloorspaces_ ;
      /**
       * <code>int32 loadedHalfFloorspaces = 11;</code>
       */
      public int getLoadedHalfFloorspaces() {
        return loadedHalfFloorspaces_;
      }
      /**
       * <code>int32 loadedHalfFloorspaces = 11;</code>
       */
      public Builder setLoadedHalfFloorspaces(int value) {
        
        loadedHalfFloorspaces_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 loadedHalfFloorspaces = 11;</code>
       */
      public Builder clearLoadedHalfFloorspaces() {
        
        loadedHalfFloorspaces_ = 0;
        onChanged();
        return this;
      }

      private boolean recipientNotHome_ ;
      /**
       * <code>bool recipientNotHome = 12;</code>
       */
      public boolean getRecipientNotHome() {
        return recipientNotHome_;
      }
      /**
       * <code>bool recipientNotHome = 12;</code>
       */
      public Builder setRecipientNotHome(boolean value) {
        
        recipientNotHome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool recipientNotHome = 12;</code>
       */
      public Builder clearRecipientNotHome() {
        
        recipientNotHome_ = false;
        onChanged();
        return this;
      }

      private boolean vacation_ ;
      /**
       * <code>bool vacation = 13;</code>
       */
      public boolean getVacation() {
        return vacation_;
      }
      /**
       * <code>bool vacation = 13;</code>
       */
      public Builder setVacation(boolean value) {
        
        vacation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool vacation = 13;</code>
       */
      public Builder clearVacation() {
        
        vacation_ = false;
        onChanged();
        return this;
      }

      private long newPickupDate_ ;
      /**
       * <code>int64 newPickupDate = 14;</code>
       */
      public long getNewPickupDate() {
        return newPickupDate_;
      }
      /**
       * <code>int64 newPickupDate = 14;</code>
       */
      public Builder setNewPickupDate(long value) {
        
        newPickupDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 newPickupDate = 14;</code>
       */
      public Builder clearNewPickupDate() {
        
        newPickupDate_ = 0L;
        onChanged();
        return this;
      }

      private boolean unknownAddress_ ;
      /**
       * <code>bool unknownAddress = 15;</code>
       */
      public boolean getUnknownAddress() {
        return unknownAddress_;
      }
      /**
       * <code>bool unknownAddress = 15;</code>
       */
      public Builder setUnknownAddress(boolean value) {
        
        unknownAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool unknownAddress = 15;</code>
       */
      public Builder clearUnknownAddress() {
        
        unknownAddress_ = false;
        onChanged();
        return this;
      }

      private boolean unknownAddressee_ ;
      /**
       * <code>bool unknownAddressee = 16;</code>
       */
      public boolean getUnknownAddressee() {
        return unknownAddressee_;
      }
      /**
       * <code>bool unknownAddressee = 16;</code>
       */
      public Builder setUnknownAddressee(boolean value) {
        
        unknownAddressee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool unknownAddressee = 16;</code>
       */
      public Builder clearUnknownAddressee() {
        
        unknownAddressee_ = false;
        onChanged();
        return this;
      }

      private boolean noGoods_ ;
      /**
       * <code>bool noGoods = 17;</code>
       */
      public boolean getNoGoods() {
        return noGoods_;
      }
      /**
       * <code>bool noGoods = 17;</code>
       */
      public Builder setNoGoods(boolean value) {
        
        noGoods_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool noGoods = 17;</code>
       */
      public Builder clearNoGoods() {
        
        noGoods_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RE)
    }

    // @@protoc_insertion_point(class_scope:RE)
    private static final nl.toefel.java.protobuf.Search.RE DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nl.toefel.java.protobuf.Search.RE();
    }

    public static nl.toefel.java.protobuf.Search.RE getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RE>
        PARSER = new com.google.protobuf.AbstractParser<RE>() {
      public RE parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RE(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RE> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RE> getParserForType() {
      return PARSER;
    }

    public nl.toefel.java.protobuf.Search.RE getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RE_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RE_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024search-request.proto\"\366\001\n\rSearchRequest" +
      "\022\r\n\005query\030\001 \001(\t\022\023\n\013page_number\030\002 \001(\005\022\027\n\017" +
      "result_per_page\030\003 \001(\005\022\020\n\010latitude\030\004 \001(\002\022" +
      "\021\n\tlongitude\030\005 \001(\002\0221\n\014shipmentType\030\006 \001(\016" +
      "2\033.SearchRequest.ShipmentType\"P\n\014Shipmen" +
      "tType\022\013\n\007UNKNOWN\020\000\022\014\n\010DELIVERY\020\001\022\n\n\006PICK" +
      "UP\020\002\022\r\n\tEXPRESSER\020\003\022\n\n\006PALLET\020\004\"\205\003\n\002RE\022\022" +
      "\n\nhtSerialNr\030\001 \001(\t\022\017\n\007routeNr\030\002 \001(\t\022\024\n\014a" +
      "ctivityCode\030\003 \001(\t\022\r\n\005ritNr\030\004 \001(\t\022\016\n\006driv" +
      "er\030\005 \001(\t\022\022\n\nshipmentNr\030\006 \001(\t\022\021\n\ttimestam",
      "p\030\007 \001(\003\022\036\n\026pickupAcceptedByDriver\030\010 \001(\010\022" +
      "\'\n\037pickupCancelledAcceptedByDriver\030\t \001(\010" +
      "\022\020\n\010pickedUp\030\n \001(\010\022\035\n\025loadedHalfFloorspa" +
      "ces\030\013 \001(\005\022\030\n\020recipientNotHome\030\014 \001(\010\022\020\n\010v" +
      "acation\030\r \001(\010\022\025\n\rnewPickupDate\030\016 \001(\003\022\026\n\016" +
      "unknownAddress\030\017 \001(\010\022\030\n\020unknownAddressee" +
      "\030\020 \001(\010\022\017\n\007noGoods\030\021 \001(\010B!\n\027nl.toefel.jav" +
      "a.protobufB\006Searchb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new java.lang.String[] { "Query", "PageNumber", "ResultPerPage", "Latitude", "Longitude", "ShipmentType", });
    internal_static_RE_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RE_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RE_descriptor,
        new java.lang.String[] { "HtSerialNr", "RouteNr", "ActivityCode", "RitNr", "Driver", "ShipmentNr", "Timestamp", "PickupAcceptedByDriver", "PickupCancelledAcceptedByDriver", "PickedUp", "LoadedHalfFloorspaces", "RecipientNotHome", "Vacation", "NewPickupDate", "UnknownAddress", "UnknownAddressee", "NoGoods", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
